config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/index', to: 'welcome#index'
  get '/prueba', to: 'printers#prueba'
  resources :printers
  resources :drivers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/driver.rb
class Driver < ApplicationRecord
    validates :model, presence: true, uniqueness: true
    validates :link, presence: true
    has_many :printers
end

app/models/printer.rb
class Printer < ApplicationRecord
  validates :serial, presence: true, uniqueness: true
  belongs_to :driver
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: %i[ show edit update destroy ]

  # GET /drivers or /drivers.json
  def index
    @drivers = Driver.order('drivers.id ASC')
  end

  # GET /drivers/1 or /drivers/1.json
  def show
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
  end

  # POST /drivers or /drivers.json
  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to driver_url(@driver), notice: "Driver agregado con éxito." }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1 or /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to driver_url(@driver), notice: "Driver actualizado con éxito." }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1 or /drivers/1.json
  def destroy
    @driver.destroy

    respond_to do |format|
      format.html { redirect_to drivers_url, notice: "Driver eliminado con éxito." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def driver_params
      params.require(:driver).permit(:model, :link)
    end
end

app/controllers/printers_controller.rb
class PrintersController < ApplicationController
  before_action :set_printer, only: %i[ show edit update destroy ]

  def prueba
  end
  # GET /printers or /printers.json
  def index
    @printers = Printer.order('printers.id ASC')
  end

  # GET /printers/1 or /printers/1.json
  def show
  end

  # GET /printers/new
  def new
    @printer = Printer.new
  end

  # GET /printers/1/edit
  def edit
  end

  # POST /printers or /printers.json
  def create
    @printer = Printer.new(printer_params)

    respond_to do |format|
      if @printer.save
        format.html { redirect_to printer_url(@printer), notice: "Impresora agregada con éxito." }
        format.json { render :show, status: :created, location: @printer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @printer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /printers/1 or /printers/1.json
  def update
    respond_to do |format|
      if @printer.update(printer_params)
        format.html { redirect_to printer_url(@printer), notice: "Impresora actualizada con éxito." }
        format.json { render :show, status: :ok, location: @printer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @printer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /printers/1 or /printers/1.json
  def destroy
    @printer.destroy

    respond_to do |format|
      format.html { redirect_to printers_url, notice: "Impresora eliminada con éxito." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_printer
      @printer = Printer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def printer_params
      params.require(:printer).permit(:name, :serial, :ip, :driver_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
    def has_color(driver)
        return true if driver[2] == "C"
    end
end

app/helpers/printers_helper.rb
module PrintersHelper
  def has_color(printer)
    return true if printer[2] == "C"
  end
  def in_range(printer)
    unless printer.nil?
      host_id = printer.split(".")
      return true if host_id[3].to_i.between?(245, 254)
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/drivers/_driver.html.erb
<% if action_name != "show" %>
  <div id="<%= dom_id driver %>" class="block">
  <% else %>
    <div id="<%= dom_id driver %>">
    <% end %>
    <div class="my-4 justify-items-end">
      <h1 class="w-fit text-center text-3xl font-bold sm:text-left" data-printer-name></h1>
      <%= driver.model %>
      <% if has_color(driver.model) %>
        <div class="rainbow outline outline-1 dark:outline-white outline-black"></div>
      <% else %>
        <div class="blckwht outline outline-1 dark:outline-white outline-black"></div>
      <% end %>
    </div>
    <div class="my-4">
      <p class="block text-xl font-bold mb-1">Controlador:</p>
      <a href="<%= driver.link %>" target="_blank" class="flex w-full items-center justify-center py-2 px-4 text-white text-sm font-medium rounded-md bg-green-700 hover:bg-green-800 focus:z-10 focus:ring-2 focus:ring-green-300 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-900">
        <svg class="mr-2 w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 3v2m6-2v2M9 19v2m6-2v2M5 9H3m2 6H3m18-6h-2m2 6h-2M7 19h10a2 2 0 002-2V7a2 2 0 00-2-2H7a2 2 0 00-2 2v10a2 2 0 002 2zM9 9h6v6H9V9z"></path></svg>
        <p>Descargar</p>
      </a>
    </div>
    <% if action_name != "show" %>
      <div class="flex items-stretch w-full rounded-md shadow-sm text-center" role="group">
        <%= link_to driver, type: "button", class: "flex w-1/3 items-center justify-center py-2 px-4 text-white text-sm font-medium rounded-l-md bg-yellow-400 hover:bg-yellow-500 focus:z-10 focus:ring-2 focus:ring-yellow-300 dark:focus:ring-yellow-900" do %>
          <svg class="mr-2 w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path></svg>
          <p>Ver</p>
        <% end %>
        <%= link_to edit_driver_path(driver), type: "button", class: "flex w-1/3 items-center justify-center py-2 px-4 text-white text-sm font-medium bg-blue-700 hover:bg-blue-800 focus:z-10 focus:ring-2 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-900" do %>
          <svg class="mr-2 w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"></path></svg>
          <p>Editar</p>
        <% end %>
        <%= link_to driver_path(driver), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, type: "button", class: "flex w-1/3 items-center justify-center py-2 px-4 text-white text-sm font-medium rounded-r-md bg-red-700 hover:bg-red-800 focus:z-10 focus:ring-2 focus:ring-red-300 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900" do %>
          <svg class="mr-2 w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg>
          <p>Eliminar</p>
        <% end %>
      </div>
      <hr class="mt-6">
    <% end %>
  </div>

app/views/drivers/edit.html.erb
<div class="vh-centrado w-11/12 pb-5 md:w-2/3 lg:w-1/2">
  <h1 class="mb-4 text-4xl font-bold">Editar Driver</h1>
  <%= render "form", driver: @driver %>
</div>

app/views/drivers/index.html.erb
<% if notice.present? %>
  <p class="mb-5 inline-block rounded-lg bg-green-50 py-2 px-3 font-medium text-green-500" id="notice"><%= notice %></p>
<% end %>
<div class="grid md:grid-flow-row md:grid-cols-2">
  <h1 class="sm:text-left mx-auto md:mx-0 mb-4 md:mb-0 text-center md:text-left text-4xl font-bold">Drivers</h1>
  <%= link_to new_driver_path, class: "flex md:ml-auto items-center justify-center rounded-md bg-blue-600 py-3 px-5 text-center font-medium text-white md:w-64" do %>
    <svg class="mr-2 h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path></svg>
    <p>Agregar un nuevo driver</p>
  <% end %>
</div>
<div class="grid md:grid-cols-2 md:gap-x-4 lg:grid-cols-3 lg:gap-x-8">
  <%= render @drivers %>
</div>

app/views/drivers/new.html.erb
<div class="vh-centrado w-11/12 pb-5 md:w-2/3 lg:w-1/2">
  <h1 class="mb-4 text-4xl font-bold">Nuevo Driver</h1>
  <%= render "form", driver: @driver %>
</div>

app/views/drivers/show.html.erb
<div class="vh-centrado w-11/12 pb-5 md:w-2/3 lg:w-1/2">
  <div class="m-auto h-full w-full">
    <% if notice.present? %>
      <p class="mb-5 inline-block rounded-lg bg-green-50 py-2 px-3 font-medium text-green-500" id="notice"><%= notice %></p>
    <% end %>
    <%= render @driver %>
    <div class="flex w-full items-stretch rounded-md text-center shadow-sm" role="group">
      <%= link_to drivers_path, type: "button", class: "flex w-1/3 items-center justify-center rounded-l-md bg-yellow-400 py-2 px-4 text-sm font-medium text-white hover:bg-yellow-500 focus:z-10 focus:ring-2 focus:ring-yellow-300 dark:focus:ring-yellow-900" do %>
        <svg class="mr-2 h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 19l-7-7 7-7m8 14l-7-7 7-7"></path></svg>
        <p>Volver</p>
      <% end %>
      <%= link_to edit_driver_path(@driver), type: "button", class: "flex w-1/3 items-center justify-center bg-blue-700 py-2 px-4 text-sm font-medium text-white hover:bg-blue-800 focus:z-10 focus:ring-2 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-900" do %>
        <svg class="mr-2 h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"></path></svg>
        <p>Editar</p>
      <% end %>
      <%= link_to driver_path(@driver), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, type: "button", class: "flex w-1/3 items-center justify-center rounded-r-md bg-red-700 py-2 px-4 text-sm font-medium text-white hover:bg-red-800 focus:z-10 focus:ring-2 focus:ring-red-300 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900" do %>
        <svg class="mr-2 h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg>
        <p>Eliminar</p>
      <% end %>
    </div>
  </div>
</div>

app/views/printers/_printer.html.erb
<% if action_name != "show" %>
  <div id="<%= dom_id printer %>" class="block" data-printer-card>
  <% else %>
    <div id="<%= dom_id printer %>">
    <% end %>
    <div class="my-4 justify-items-end">
    <% if printer.id > 900 %>
      <h1 class="w-fit text-center text-3xl font-bold sm:text-left outline outline-8 outline-red-300 bg-red-300 dark:bg-red-700 dark:outline-red-700 rounded-sm" data-printer-name>
    <% else %>
      <h1 class="w-fit text-center text-3xl font-bold sm:text-left" data-printer-name>
    <% end %>
      
        <%= printer.name %>
        <% if has_color(printer.driver.model) %>
          <div class="rainbow outline outline-1 dark:outline-white outline-black"></div>
        <% else %>
          <div class="blckwht outline outline-1 dark:outline-white outline-black"></div>
        <% end %>
      </h1>
    </div>
    <div class="my-4 grid grid-cols-2">
      <div>
        <p class="mb-1 block text-xl font-bold">Modelo:</p>
        <p data-printer-model><%= printer.driver.model %></p>
      </div>
      <div>
        <p class="mb-1 block text-xl font-bold">Serial:</p>
        <p data-printer-serial><%= printer.serial %></p>
      </div>
    </div>
    <div class="mt-5 grid grid-cols-2">
      <p class="mb-1 block text-xl font-bold">Dirección IP:</p>
      <p class="mb-1 block text-xl font-bold">Controlador:</p>
    </div>
    <div class="mb-5 flex w-full items-stretch rounded-md text-center shadow-sm" role="group">
      <% if in_range(printer.ip) %>
      <a href="http://<%= printer.ip %>" target="_blank" class="flex w-1/2 items-center justify-center rounded-l-md bg-purple-400 py-2 px-4 text-sm font-medium text-white hover:bg-purple-500 focus:z-10 focus:ring-2 focus:ring-purple-300 dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-900">
        <svg class="mr-2 h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9"></path></svg>
          <p><%= printer.ip %></p>
      <% else %>
      <a href="http://<%= printer.ip %>" data-tooltip-target="tooltip-default" target="_blank" class="flex w-1/2 items-center justify-center rounded-l-md bg-purple-400 py-2 px-4 text-sm font-medium text-white hover:bg-purple-500 focus:z-10 focus:ring-2 focus:ring-purple-300 dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-900">
        <svg class="mr-2 h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9"></path></svg>
        <p class="underline decoration-red-600 decoration-4"><%= printer.ip %></p>
        <div id="tooltip-default" role="tooltip" class="inline-block absolute invisible z-10 py-2 px-3 text-sm font-medium text-white bg-gray-900 rounded-lg shadow-sm opacity-0 transition-opacity duration-300 tooltip dark:bg-gray-700">
          Dirección IP de la imperesora fuera del rango
          <div class="tooltip-arrow" data-popper-arrow></div>
        </div>
      <% end %>
      </a>
      <a href="<%= printer.driver.link %>" target="_blank" class="flex w-1/2 items-center justify-center rounded-r-md bg-green-700 py-2 px-4 text-sm font-medium text-white hover:bg-green-800 focus:z-10 focus:ring-2 focus:ring-green-300 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-900">
        <svg class="mr-2 h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 3v2m6-2v2M9 19v2m6-2v2M5 9H3m2 6H3m18-6h-2m2 6h-2M7 19h10a2 2 0 002-2V7a2 2 0 00-2-2H7a2 2 0 00-2 2v10a2 2 0 002 2zM9 9h6v6H9V9z"></path></svg>
        <p>Descargar</p>
      </a>
    </div>
    <% if action_name != "show" %>
      <div class="flex w-full items-stretch rounded-md text-center shadow-sm" role="group">
        <%= link_to printer, type: "button", class: "flex w-1/3 items-center justify-center py-2 px-4 text-white text-sm font-medium rounded-l-md bg-yellow-400 hover:bg-yellow-500 focus:z-10 focus:ring-2 focus:ring-yellow-300 dark:focus:ring-yellow-900" do %>
          <svg class="mr-2 w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path></svg>
          <p>Ver</p>
        <% end %>
        <%= link_to edit_printer_path(printer), type: "button", class: "flex w-1/3 items-center justify-center py-2 px-4 text-white text-sm font-medium bg-blue-700 hover:bg-blue-800 focus:z-10 focus:ring-2 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-900" do %>
          <svg class="mr-2 h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"></path></svg>
          <p>Editar</p>
        <% end %>
        <%= link_to printer_path(printer), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, type: "button", class: "flex w-1/3 items-center justify-center py-2 px-4 text-white text-sm font-medium rounded-r-md bg-red-700 hover:bg-red-800 focus:z-10 focus:ring-2 focus:ring-red-300 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900" do %>
          <svg class="mr-2 h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg>
          <p>Eliminar</p>
        <% end %>
      </div>
      <hr class="mt-6">
    <% end %>
  </div>

app/views/printers/edit.html.erb
<div class="vh-centrado w-11/12 pb-5 md:w-2/3 lg:w-1/2">
  <h1 class="mb-4 text-4xl font-bold">Editar Impresora</h1>
  <%= render "form", printer: @printer %>
</div>

app/views/printers/show.html.erb
<div class="vh-centrado w-11/12 pb-5 md:w-2/3 lg:w-1/2">
  <div class="m-auto h-full w-full">
    <% if notice.present? %>
      <p class="mb-5 inline-block rounded-lg bg-green-50 py-2 px-3 font-medium text-green-500" id="notice"><%= notice %></p>
    <% end %>
    <%= render @printer %>
    <div class="flex w-full items-stretch rounded-md text-center shadow-sm" role="group">
      <%= link_to printers_path, type: "button", class: "flex w-1/3 items-center justify-center rounded-l-md bg-yellow-400 py-2 px-4 text-sm font-medium text-white hover:bg-yellow-500 focus:z-10 focus:ring-2 focus:ring-yellow-300 dark:focus:ring-yellow-900" do %>
        <svg class="mr-2 h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 19l-7-7 7-7m8 14l-7-7 7-7"></path></svg>
        <p>Volver</p>
      <% end %>
      <%= link_to edit_printer_path(@printer), type: "button", class: "flex w-1/3 items-center justify-center bg-blue-700 py-2 px-4 text-sm font-medium text-white hover:bg-blue-800 focus:z-10 focus:ring-2 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-900" do %>
        <svg class="mr-2 h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"></path></svg>
        <p>Editar</p>
      <% end %>
      <%= link_to printer_path(@printer), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, type: "button", class: "flex w-1/3 items-center justify-center rounded-r-md bg-red-700 py-2 px-4 text-sm font-medium text-white hover:bg-red-800 focus:z-10 focus:ring-2 focus:ring-red-300 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900" do %>
        <svg class="mr-2 h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg>
        <p>Eliminar</p>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="vh-centrado grid w-full items-stretch gap-16 px-16 text-center sm:gap-x-4 md:grid-cols-2 md:px-32 lg:gap-x-8 lg:px-64 xl:px-64" role="group">
  <%= link_to printers_path, type: "button", class: "w-auto items-center justify-center rounded-md bg-blue-700 py-2 px-4 text-sm font-medium text-white hover:bg-blue-800 focus:z-10 focus:ring-2 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-900" do %>
    <svg class="block m-auto my-2 w-16 md:w-32 h-24 md:h-24" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"></path></svg>
    <p class="my-2 text-3xl md:text-2xl lg:text-xl">Impresoras</p>
  <% end %>
  <%= link_to drivers_path, type: "button", class: "w-auto items-center justify-center rounded-md bg-blue-700 py-2 px-4 text-sm font-medium text-white hover:bg-blue-800 focus:z-10 focus:ring-2 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-900" do %>
    <svg class="block m-auto my-2 w-16 md:w-32 h-24 md:h-24" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 3v2m6-2v2M9 19v2m6-2v2M5 9H3m2 6H3m18-6h-2m2 6h-2M7 19h10a2 2 0 002-2V7a2 2 0 00-2-2H7a2 2 0 00-2 2v10a2 2 0 002 2zM9 9h6v6H9V9z"></path></svg>
    <p class="my-2 text-3xl md:text-2xl lg:text-xl">Controladores</p>
  <% end %>
</div>